" Food & drink
ab :pizza:		🍕
ab :grapes:		🍇
ab :melon:		🍈
ab :watermelon: 🍉 
ab :tangerine: 🍊
ab :lemon: 🍋
ab :banana: 🍌 
ab :pineapple: 🍍
ab :mango: 🥭
ab :red_apple: 🍎
ab :green_apple: 🍏
ab :pear: 🍐
ab :peach: 🍑
ab :cherries: 🍒
ab :strawberry: 🍓
ab :blueberries: 🫐
ab :kiwi_fruit: 🥝
ab :tomato: 🍅
ab :olive: 🫒
ab :coconut: 🥥
ab :avocado:  🥑
ab :eggplant: 🍆
ab :potato:   🥔
ab :carrot:   🥕
ab :ear_of_corn: 🌽
ab :hot_pepper: 🌶️
ab :bell_pepper: 🫑
ab :cucumber: 🥒 
ab :leafy_green: 🥬 
ab :broccoli: 🥦 
ab :garlic: 🧄 
ab :onion: 🧅 
ab :mushroom: 🍄 
ab :peanuts: 🥜 
ab :chestnut: 🌰 
ab :bread: 🍞 
ab :croissant: 🥐 
ab :baguette_bread: 🥖 
ab :flatbread: 🫓 
ab :pretzel: 🥨 
ab :bagel: 🥯 
ab :pancakes: 🥞 
ab :waffle: 🧇 
ab :cheese_wedge: 🧀 
ab :meat_on_bone: 🍖 
ab :poultry_leg: 🍗 
ab :cut_of_meat: 🥩 
ab :bacon: 🥓 
ab :hamburger: 🍔 
ab :french_fries: 🍟 
ab :pizza: 🍕 
ab :hot_dog: 🌭 
ab :sandwich: 🥪 
ab :taco: 🌮 
ab :burrito: 🌯 
ab :tamale: 🫔 
ab :stuffed_flatbread: 🥙 
ab :falafel: 🧆 
ab :egg: 🥚 
ab :cooking: 🍳 
ab :shallow_pan_of_food: 🥘 
ab :pot_of_food: 🍲 
ab :fondue: 🫕 
ab :bowl_with_spoon: 🥣 
ab :green_salad: 🥗 
ab :popcorn: 🍿 
ab :butter: 🧈 
ab :salt: 🧂 
ab :canned_food: 🥫 
ab :bento_box: 🍱 
ab :rice_cracker: 🍘 
ab :rice_ball: 🍙 
ab :cooked_rice: 🍚 
ab :curry_rice: 🍛 
ab :steaming_bowl: 🍜 
ab :spaghetti: 🍝 
ab :roasted_sweet_potato: 🍠 
ab :oden: 🍢 
ab :sushi: 🍣 
ab :fried_shrimp: 🍤 
ab :fish_cake_with_swirl: 🍥 
ab :moon_cake: 🥮 
ab :dango: 🍡 
ab :dumpling: 🥟 
ab :fortune_cookie: 🥠 
ab :takeout_box: 🥡 
ab :oyster: 🦪 
ab :soft_ice_cream: 🍦 
ab :shaved_ice: 🍧 
ab :ice_cream: 🍨 
ab :doughnut: 🍩 
ab :cookie: 🍪 
ab :birthday_cake: 🎂 
ab :shortcake: 🍰 
ab :cupcake: 🧁 
ab :pie: 🥧 
ab :chocolate_bar: 🍫 
ab :candy: 🍬 
ab :lollipop: 🍭 
ab :custard: 🍮 
ab :honey_pot: 🍯 
ab :baby_bottle: 🍼 
ab :glass_of_milk: 🥛 
ab :hot_beverage: ☕ 
ab :teapot: 🫖 
ab :teacup_without_handle: 🍵 
ab :sake: 🍶 
ab :bottle_with_popping_cork: 🍾 
ab :wine_glass: 🍷 
ab :cocktail_glass: 🍸 
ab :tropical_drink: 🍹 
ab :beer_mug: 🍺 
ab :clinking_beer_mugs: 🍻 
ab :clinking_glasses: 🥂 
ab :tumbler_glass: 🥃 
ab :cup_with_straw: 🥤 
ab :bubble_tea: 🧋 
ab :beverage_box: 🧃 
ab :mate: 🧉 
ab :ice: 🧊 
ab :chopsticks: 🥢 
ab :️fork_and_knife_with_plate: 🍽 
ab :fork_and_knife: 🍴 
ab :spoon: 🥄 

