" Symbols

ab :heart_with_arrow: 💘 
ab :heart_with_ribbon: 💝 
ab :sparkling_heart: 💖 
ab :growing_heart: 💗 
ab :beating_heart: 💓 
ab :revolving_hearts: 💞 
ab :two_hearts: 💕 
ab :heart_decoration: 💟 
ab :️heart_exclamation: ❣ 
ab :broken_heart: 💔 
ab :️heart_on_fire: ❤ ‍🔥
ab :️mending_heart: ❤ ‍🩹
ab :️red_heart: ❤ 
ab :orange_heart: 🧡 
ab :yellow_heart: 💛 
ab :green_heart: 💚 
ab :blue_heart: 💙 
ab :purple_heart: 💜 
ab :brown_heart: 🤎 
ab :black_heart: 🖤 
ab :white_heart: 🤍 
ab :hundred_points: 💯 
ab :anger_symbol: 💢 
ab :speech_balloon: 💬 
ab :️eye_in_speech_bubble: 👁 ‍🗨️
ab :️left_speech_bubble: 🗨 
ab :️right_anger_bubble: 🗯 
ab :thought_balloon: 💭 
ab :zzz: 💤 
ab :white_flower: 💮 
ab :️hot_springs: ♨ 
ab :barber_pole: 💈 
ab :stop_sign: 🛑 
ab :twelve_o’clock: 🕛 
ab :twelve_thirty: 🕧 
ab :one_o’clock: 🕐 
ab :one_thirty: 🕜 
ab :two_o’clock: 🕑 
ab :two_thirty: 🕝 
ab :three_o’clock: 🕒 
ab :three_thirty: 🕞 
ab :four_o’clock: 🕓 
ab :four_thirty: 🕟 
ab :five_o’clock: 🕔 
ab :five_thirty: 🕠 
ab :six_o’clock: 🕕 
ab :six_thirty: 🕡 
ab :seven_o’clock: 🕖 
ab :seven_thirty: 🕢 
ab :eight_o’clock: 🕗 
ab :eight_thirty: 🕣 
ab :nine_o’clock: 🕘 
ab :nine_thirty: 🕤 
ab :ten_o’clock: 🕙 
ab :ten_thirty: 🕥 
ab :eleven_o’clock: 🕚 
ab :eleven_thirty: 🕦 
ab :cyclone: 🌀 
ab :️spade_suit: ♠ 
ab :️heart_suit: ♥ 
ab :️diamond_suit: ♦ 
ab :️club_suit: ♣ 
ab :joker: 🃏 
ab :mahjong_red_dragon: 🀄 
ab :flower_playing_cards: 🎴 
ab :muted_speaker: 🔇 
ab :speaker_low_volume: 🔈 
ab :speaker_medium_volume: 🔉 
ab :speaker_high_volume: 🔊 
ab :loudspeaker: 📢 
ab :megaphone: 📣 
ab :postal_horn: 📯 
ab :bell: 🔔 
ab :bell_with_slash: 🔕 
ab :musical_note: 🎵 
ab :musical_notes: 🎶 
ab :chart_increasing_with_yen: 💹 
ab :elevator: 🛗 
ab :atm_sign: 🏧 
ab :litter_in_bin_sign: 🚮 
ab :potable_water: 🚰 
ab :wheelchair_symbol: ♿ 
ab :men’s_room: 🚹 
ab :women’s_room: 🚺 
ab :restroom: 🚻 
ab :baby_symbol: 🚼 
ab :water_closet: 🚾 
ab :️warning: ⚠ 
ab :children_crossing: 🚸 
ab :no_entry: ⛔ 
ab :prohibited: 🚫 
ab :no_bicycles: 🚳 
ab :no_smoking: 🚭 
ab :no_littering: 🚯 
ab :non_potable_water: 🚱 
ab :no_pedestrians: 🚷 
ab :no_mobile_phones: 📵 
ab :no_one_under_eighteen: 🔞 
ab :️radioactive: ☢ 
ab :️biohazard: ☣ 
ab :️up_arrow: ⬆ 
ab :️up_right_arrow: ↗ 
ab :️right_arrow: ➡ 
ab :️down_right_arrow: ↘ 
ab :️down_arrow: ⬇ 
ab :️down_left_arrow: ↙ 
ab :️left_arrow: ⬅ 
ab :️up_left_arrow: ↖ 
ab :️up_down_arrow: ↕ 
ab :️left_right_arrow: ↔ 
ab :️right_arrow_curving_left: ↩ 
ab :️left_arrow_curving_right: ↪ 
ab :️right_arrow_curving_up: ⤴ 
ab :️right_arrow_curving_down: ⤵ 
ab :clockwise_vertical_arrows: 🔃 
ab :counterclockwise_arrows_button: 🔄 
ab :back_arrow: 🔙 
ab :end_arrow: 🔚 
ab :on!_arrow: 🔛 
ab :soon_arrow: 🔜 
ab :top_arrow: 🔝 
ab :place_of_worship: 🛐 
ab :️atom_symbol: ⚛ 
ab :️om: 🕉 
ab :️star_of_david: ✡ 
ab :️wheel_of_dharma: ☸ 
ab :️yin_yang: ☯ 
ab :️latin_cross: ✝ 
ab :️orthodox_cross: ☦ 
ab :️star_and_crescent: ☪ 
ab :️peace_symbol: ☮ 
ab :menorah: 🕎 
ab :dotted_six_pointed_star: 🔯 
ab :aries: ♈ 
ab :taurus: ♉ 
ab :gemini: ♊ 
ab :cancer: ♋ 
ab :leo: ♌ 
ab :virgo: ♍ 
ab :libra: ♎ 
ab :scorpio: ♏ 
ab :sagittarius: ♐ 
ab :capricorn: ♑ 
ab :aquarius: ♒ 
ab :pisces: ♓ 
ab :ophiuchus: ⛎ 
ab :shuffle_tracks_button: 🔀 
ab :repeat_button: 🔁 
ab :repeat_single_button: 🔂 
ab :️play_button: ▶ 
ab :fast_forward_button: ⏩ 
ab :️next_track_button: ⏭ 
ab :️play_or_pause_button: ⏯ 
ab :️reverse_button: ◀ 
ab :fast_reverse_button: ⏪ 
ab :️last_track_button: ⏮ 
ab :upwards_button: 🔼 
ab :fast_up_button: ⏫ 
ab :downwards_button: 🔽 
ab :fast_down_button: ⏬ 
ab :️pause_button: ⏸ 
ab :️stop_button: ⏹ 
ab :️record_button: ⏺ 
ab :️eject_button: ⏏ 
ab :cinema: 🎦 
ab :dim_button: 🔅 
ab :bright_button: 🔆 
ab :antenna_bars: 📶 
ab :vibration_mode: 📳 
ab :mobile_phone_off: 📴 
ab :️female_sign: ♀ 
ab :️male_sign: ♂ 
ab :️multiply: ✖ 
ab :plus: ➕ 
ab :minus: ➖ 
ab :divide: ➗ 
ab :️infinity: ♾ 
ab :️double_exclamation_mark: ‼ 
ab :️exclamation_question_mark: ⁉ 
ab :red_question_mark: ❓ 
ab :white_question_mark: ❔ 
ab :white_exclamation_mark: ❕ 
ab :red_exclamation_mark: ❗ 
ab :️wavy_dash: 〰 
ab :currency_exchange: 💱 
ab :heavy_dollar_sign: 💲 
ab :️medical_symbol: ⚕ 
ab :️recycling_symbol: ♻ 
ab :️fleur_de_lis: ⚜ 
ab :trident_emblem: 🔱 
ab :name_badge: 📛 
ab :japanese_symbol_for_beginner: 🔰 
ab :hollow_red_circle: ⭕ 
ab :check_mark_button: ✅ 
ab :️check_box_with_check: ☑ 
ab :️check_mark: ✔ 
ab :cross_mark: ❌ 
ab :cross_mark_button: ❎ 
ab :curly_loop: ➰ 
ab :double_curly_loop: ➿ 
ab :️part_alternation_mark: 〽 
ab :️eight_spoked_asterisk: ✳ 
ab :️eight_pointed_star: ✴ 
ab :️sparkle: ❇ 
ab :️copyright: © 
ab :️registered: ® 
ab :️trade_mark: ™ 
ab :keycap_number_sign: #️⃣
ab :️keycap_asterisk: *️⃣ 
ab :️keycap_digit_zero: 0️⃣
ab :️keycap_digit_one: 1️⃣
ab :️keycap_digit_two: 2️⃣
ab :️keycap_digit_three: 3️⃣ 
ab :️keycap_digit_four: 4️⃣
ab :️keycap_digit_five: 5️⃣
ab :️keycap_digit_six:  6️⃣
ab :️keycap_digit_seven: 7️⃣
ab :️keycap_digit_eight: 8️⃣
ab :️keycap_digit_nine: 9️⃣
ab :keycap_10: 🔟 
ab :input_latin_uppercase: 🔠 
ab :input_latin_lowercase: 🔡 
ab :input_numbers: 🔢 
ab :input_symbols: 🔣 
ab :input_latin_letters: 🔤 
ab :️a_button_(blood_type): 🅰 
ab :ab_button_(blood_type): 🆎 
ab :️b_button_(blood_type): 🅱 
ab :cl_button: 🆑 
ab :cool_button: 🆒 
ab :free_button: 🆓 
ab :️information: ℹ 
ab :id_button: 🆔 
ab :️circled_m: ⓜ 
ab :new_button: 🆕 
ab :ng_button: 🆖 
ab :️o_button_(blood_type): 🅾 
ab :ok_button: 🆗 
ab :️p_button: 🅿 
ab :sos_button: 🆘 
ab :up!_button: 🆙 
ab :vs_button: 🆚 
ab :japanese_“here”_button: 🈁 
ab :️japanese_“service_charge”_button: 🈂 
ab :️japanese_“monthly_amount”_button: 🈷 
ab :japanese_“not_free_of_charge”_button: 🈶 
ab :japanese_“reserved”_button: 🈯 
ab :japanese_“bargain”_button: 🉐 
ab :japanese_“discount”_button: 🈹 
ab :japanese_“free_of_charge”_button: 🈚 
ab :japanese_“prohibited”_button: 🈲 
ab :japanese_“acceptable”_button: 🉑 
ab :japanese_“application”_button: 🈸 
ab :japanese_“passing_grade”_button: 🈴 
ab :japanese_“vacancy”_button: 🈳 
ab :️japanese_“congratulations”_button: ㊗ 
ab :️japanese_“secret”_button: ㊙ 
ab :japanese_“open_for_business”_button: 🈺 
ab :japanese_“no_vacancy”_button: 🈵 
ab :red_circle: 🔴 
ab :orange_circle: 🟠 
ab :yellow_circle: 🟡 
ab :green_circle: 🟢 
ab :blue_circle: 🔵 
ab :purple_circle: 🟣 
ab :brown_circle: 🟤 
ab :black_circle: ⚫ 
ab :white_circle: ⚪ 
ab :red_square: 🟥 
ab :orange_square: 🟧 
ab :yellow_square: 🟨 
ab :green_square: 🟩 
ab :blue_square: 🟦 
ab :purple_square: 🟪 
ab :brown_square: 🟫 
ab :black_large_square: ⬛ 
ab :white_large_square: ⬜ 
ab :️black_medium_square: ◼ 
ab :️white_medium_square: ◻ 
ab :black_medium_small_square: ◾ 
ab :white_medium_small_square: ◽ 
ab :️black_small_square: ▪ 
ab :️white_small_square: ▫ 
ab :large_orange_diamond: 🔶 
ab :large_blue_diamond: 🔷 
ab :small_orange_diamond: 🔸 
ab :small_blue_diamond: 🔹 
ab :red_triangle_pointed_up: 🔺 
ab :red_triangle_pointed_down: 🔻 
ab :diamond_with_a_dot: 💠 
ab :radio_button: 🔘 
ab :white_square_button: 🔳 
ab :black_square_button: 🔲 
