" Animals & Nature
ab :see_no_evil_monkey: 🙈 
ab :hear_no_evil_monkey: 🙉 
ab :speak_no_evil_monkey: 🙊 
ab :collision: 💥 
ab :dizzy: 💫 
ab :sweat_droplets: 💦 
ab :dashing_away: 💨 
ab :monkey_face: 🐵 
ab :monkey: 🐒 
ab :gorilla: 🦍 
ab :orangutan: 🦧 
ab :dog_face: 🐶 
ab :dog: 🐕 
ab :guide_dog: 🦮 
ab :service_dog: 🐕 ‍🦺
ab :poodle: 🐩 
ab :wolf: 🐺 
ab :fox: 🦊 
ab :raccoon: 🦝 
ab :cat_face: 🐱 
ab :cat: 🐈 
ab :black_cat: 🐈 ‍⬛
ab :lion: 🦁 
ab :tiger_face: 🐯 
ab :tiger: 🐅 
ab :leopard: 🐆 
ab :horse_face: 🐴 
ab :horse: 🐎 
ab :unicorn: 🦄 
ab :zebra: 🦓 
ab :deer: 🦌 
ab :bison: 🦬 
ab :cow_face: 🐮 
ab :ox: 🐂 
ab :water_buffalo: 🐃 
ab :cow: 🐄 
ab :pig_face: 🐷 
ab :pig: 🐖 
ab :boar: 🐗 
ab :pig_nose: 🐽 
ab :ram: 🐏 
ab :ewe: 🐑 
ab :goat: 🐐 
ab :camel: 🐪 
ab :two_hump_camel: 🐫 
ab :llama: 🦙 
ab :giraffe: 🦒 
ab :elephant: 🐘 
ab :mammoth: 🦣 
ab :rhinoceros: 🦏 
ab :hippopotamus: 🦛 
ab :mouse_face: 🐭 
ab :mouse: 🐁 
ab :rat: 🐀 
ab :hamster: 🐹 
ab :rabbit_face: 🐰 
ab :rabbit: 🐇 
ab :️chipmunk: 🐿 
ab :beaver: 🦫 
ab :hedgehog: 🦔 
ab :bat: 🦇 
ab :bear: 🐻 
ab :polar_bear: 🐻 ‍❄️
ab :koala: 🐨 
ab :panda: 🐼 
ab :sloth: 🦥 
ab :otter: 🦦 
ab :skunk: 🦨 
ab :kangaroo: 🦘 
ab :badger: 🦡 
ab :paw_prints: 🐾 
ab :turkey: 🦃 
ab :chicken: 🐔 
ab :rooster: 🐓 
ab :hatching_chick: 🐣 
ab :baby_chick: 🐤 
ab :front_facing_baby_chick: 🐥 
ab :bird: 🐦 
ab :penguin: 🐧 
ab :️dove: 🕊 
ab :eagle: 🦅 
ab :duck: 🦆 
ab :swan: 🦢 
ab :owl: 🦉 
ab :dodo: 🦤 
ab :feather: 🪶 
ab :flamingo: 🦩 
ab :peacock: 🦚 
ab :parrot: 🦜 
ab :frog: 🐸 
ab :crocodile: 🐊 
ab :turtle: 🐢 
ab :lizard: 🦎 
ab :snake: 🐍 
ab :dragon_face: 🐲 
ab :dragon: 🐉 
ab :sauropod: 🦕 
ab :t_rex: 🦖 
ab :spouting_whale: 🐳 
ab :whale: 🐋 
ab :dolphin: 🐬 
ab :seal: 🦭 
ab :fish: 🐟 
ab :tropical_fish: 🐠 
ab :blowfish: 🐡 
ab :shark: 🦈 
ab :octopus: 🐙 
ab :spiral_shell: 🐚 
ab :snail: 🐌 
ab :butterfly: 🦋 
ab :bug: 🐛 
ab :ant: 🐜 
ab :honeybee: 🐝 
ab :beetle: 🪲 
ab :lady_beetle: 🐞 
ab :cricket: 🦗 
ab :cockroach: 🪳 
ab :️spider: 🕷 
ab :️spider_web: 🕸 
ab :scorpion: 🦂 
ab :mosquito: 🦟 
ab :fly: 🪰 
ab :worm: 🪱 
ab :microbe: 🦠 
ab :bouquet: 💐 
ab :cherry_blossom: 🌸 
ab :white_flower: 💮 
ab :️rosette: 🏵 
ab :rose: 🌹 
ab :wilted_flower: 🥀 
ab :hibiscus: 🌺 
ab :sunflower: 🌻 
ab :blossom: 🌼 
ab :tulip: 🌷 
ab :seedling: 🌱 
ab :potted_plant: 🪴 
ab :evergreen_tree: 🌲 
ab :deciduous_tree: 🌳 
ab :palm_tree: 🌴 
ab :cactus: 🌵 
ab :sheaf_of_rice: 🌾 
ab :herb: 🌿 
ab :️shamrock: ☘ 
ab :four_leaf_clover: 🍀 
ab :maple_leaf: 🍁 
ab :fallen_leaf: 🍂 
ab :leaf_fluttering_in_wind: 🍃 
ab :mushroom: 🍄 
ab :chestnut: 🌰 
ab :crab: 🦀 
ab :lobster: 🦞 
ab :shrimp: 🦐 
ab :squid: 🦑 
ab :globe_showing_europe_africa: 🌍 
ab :globe_showing_americas: 🌎 
ab :globe_showing_asia_australia: 🌏 
ab :globe_with_meridians: 🌐 
ab :rock: 🪨 
ab :new_moon: 🌑 
ab :waxing_crescent_moon: 🌒 
ab :first_quarter_moon: 🌓 
ab :waxing_gibbous_moon: 🌔 
ab :full_moon: 🌕 
ab :waning_gibbous_moon: 🌖 
ab :last_quarter_moon: 🌗 
ab :waning_crescent_moon: 🌘 
ab :crescent_moon: 🌙 
ab :new_moon_face: 🌚 
ab :first_quarter_moon_face: 🌛 
ab :last_quarter_moon_face: 🌜 
ab :️sun: ☀ 
ab :full_moon_face: 🌝 
ab :sun_with_face: 🌞 
ab :star: ⭐ 
ab :glowing_star: 🌟 
ab :shooting_star: 🌠 
ab :️cloud: ☁ 
ab :sun_behind_cloud: ⛅ 
ab :️cloud_with_lightning_and_rain: ⛈ 
ab :️sun_behind_small_cloud: 🌤 
ab :️sun_behind_large_cloud: 🌥 
ab :️sun_behind_rain_cloud: 🌦 
ab :️cloud_with_rain: 🌧 
ab :️cloud_with_snow: 🌨 
ab :️cloud_with_lightning: 🌩 
ab :️tornado: 🌪 
ab :️fog: 🌫 
ab :️wind_face: 🌬 
ab :rainbow: 🌈 
ab :️umbrella: ☂ 
ab :umbrella_with_rain_drops: ☔ 
ab :high_voltage: ⚡ 
ab :️snowflake: ❄ 
ab :️snowman: ☃ 
ab :snowman_without_snow: ⛄ 
ab :️comet: ☄ 
ab :fire: 🔥 
ab :droplet: 💧 
ab :water_wave: 🌊 
ab :christmas_tree: 🎄 
ab :sparkles: ✨ 
ab :tanabata_tree: 🎋 
ab :pine_decoration: 🎍 
