" Objects

ab :love_letter: 💌 
ab :️hole: 🕳 
ab :bomb: 💣 
ab :person_taking_bath: 🛀 
ab :person_in_bed: 🛌 
ab :kitchen_knife: 🔪 
ab :amphora: 🏺 
ab :️world_map: 🗺 
ab :compass: 🧭 
ab :brick: 🧱 
ab :barber_pole: 💈 
ab :manual_wheelchair: 🦽 
ab :motorized_wheelchair: 🦼 
ab :️oil_drum: 🛢 
ab :️bellhop_bell: 🛎 
ab :luggage: 🧳 
ab :hourglass_done: ⌛ 
ab :hourglass_not_done: ⏳ 
ab :watch: ⌚ 
ab :alarm_clock: ⏰ 
ab :️stopwatch: ⏱ 
ab :️timer_clock: ⏲ 
ab :️mantelpiece_clock: 🕰 
ab :️thermometer: 🌡 
ab :️umbrella_on_ground: ⛱ 
ab :firecracker: 🧨 
ab :balloon: 🎈 
ab :party_popper: 🎉 
ab :confetti_ball: 🎊 
ab :japanese_dolls: 🎎 
ab :carp_streamer: 🎏 
ab :wind_chime: 🎐 
ab :red_envelope: 🧧 
ab :ribbon: 🎀 
ab :wrapped_gift: 🎁 
ab :diving_mask: 🤿 
ab :yo_yo: 🪀 
ab :kite: 🪁 
ab :crystal_ball: 🔮 
ab :magic_wand: 🪄 
ab :nazar_amulet: 🧿 
ab :️joystick: 🕹 
ab :teddy_bear: 🧸 
ab :piñata: 🪅 
ab :nesting_dolls: 🪆 
ab :️framed_picture: 🖼 
ab :thread: 🧵 
ab :sewing_needle: 🪡 
ab :yarn: 🧶 
ab :knot: 🪢 
ab :️shopping_bags: 🛍 
ab :prayer_beads: 📿 
ab :gem_stone: 💎 
ab :postal_horn: 📯 
ab :️studio_microphone: 🎙 
ab :️level_slider: 🎚 
ab :️control_knobs: 🎛 
ab :radio: 📻 
ab :banjo: 🪕 
ab :mobile_phone: 📱 
ab :mobile_phone_with_arrow: 📲 
ab :️telephone: ☎ 
ab :telephone_receiver: 📞 
ab :pager: 📟 
ab :fax_machine: 📠 
ab :battery: 🔋 
ab :electric_plug: 🔌 
ab :laptop: 💻 
ab :️desktop_computer: 🖥 
ab :️printer: 🖨 
ab :️keyboard: ⌨ 
ab :️computer_mouse: 🖱 
ab :️trackball: 🖲 
ab :computer_disk: 💽 
ab :floppy_disk: 💾 
ab :optical_disk: 💿 
ab :dvd: 📀 
ab :abacus: 🧮 
ab :movie_camera: 🎥 
ab :️film_frames: 🎞 
ab :️film_projector: 📽 
ab :television: 📺 
ab :camera: 📷 
ab :camera_with_flash: 📸 
ab :video_camera: 📹 
ab :videocassette: 📼 
ab :magnifying_glass_tilted_left: 🔍 
ab :magnifying_glass_tilted_right: 🔎 
ab :️candle: 🕯 
ab :light_bulb: 💡 
ab :flashlight: 🔦 
ab :red_paper_lantern: 🏮 
ab :diya_lamp: 🪔 
ab :notebook_with_decorative_cover: 📔 
ab :closed_book: 📕 
ab :open_book: 📖 
ab :green_book: 📗 
ab :blue_book: 📘 
ab :orange_book: 📙 
ab :books: 📚 
ab :notebook: 📓 
ab :ledger: 📒 
ab :page_with_curl: 📃 
ab :scroll: 📜 
ab :page_facing_up: 📄 
ab :newspaper: 📰 
ab :️rolled_up_newspaper: 🗞 
ab :bookmark_tabs: 📑 
ab :bookmark: 🔖 
ab :️label: 🏷 
ab :money_bag: 💰 
ab :coin: 🪙 
ab :yen_banknote: 💴 
ab :dollar_banknote: 💵 
ab :euro_banknote: 💶 
ab :pound_banknote: 💷 
ab :money_with_wings: 💸 
ab :credit_card: 💳 
ab :receipt: 🧾 
ab :️envelope: ✉ 
ab :e_mail: 📧 
ab :incoming_envelope: 📨 
ab :envelope_with_arrow: 📩 
ab :outbox_tray: 📤 
ab :inbox_tray: 📥 
ab :package: 📦 
ab :closed_mailbox_with_raised_flag: 📫 
ab :closed_mailbox_with_lowered_flag: 📪 
ab :open_mailbox_with_raised_flag: 📬 
ab :open_mailbox_with_lowered_flag: 📭 
ab :postbox: 📮 
ab :️ballot_box_with_ballot: 🗳 
ab :️pencil: ✏ 
ab :️black_nib: ✒ 
ab :️fountain_pen: 🖋 
ab :️pen: 🖊 
ab :️paintbrush: 🖌 
ab :️crayon: 🖍 
ab :memo: 📝 
ab :file_folder: 📁 
ab :open_file_folder: 📂 
ab :️card_index_dividers: 🗂 
ab :calendar: 📅 
ab :tear_off_calendar: 📆 
ab :️spiral_notepad: 🗒 
ab :️spiral_calendar: 🗓 
ab :card_index: 📇 
ab :chart_increasing: 📈 
ab :chart_decreasing: 📉 
ab :bar_chart: 📊 
ab :clipboard: 📋 
ab :pushpin: 📌 
ab :round_pushpin: 📍 
ab :paperclip: 📎 
ab :️linked_paperclips: 🖇 
ab :straight_ruler: 📏 
ab :triangular_ruler: 📐 
ab :️scissors: ✂ 
ab :️card_file_box: 🗃 
ab :️file_cabinet: 🗄 
ab :️wastebasket: 🗑 
ab :locked: 🔒 
ab :unlocked: 🔓 
ab :locked_with_pen: 🔏 
ab :locked_with_key: 🔐 
ab :key: 🔑 
ab :️old_key: 🗝 
ab :hammer: 🔨 
ab :axe: 🪓 
ab :️pick: ⛏ 
ab :️hammer_and_pick: ⚒ 
ab :️hammer_and_wrench: 🛠 
ab :️dagger: 🗡 
ab :️crossed_swords: ⚔ 
ab :water_pistol: 🔫 
ab :boomerang: 🪃 
ab :️shield: 🛡 
ab :carpentry_saw: 🪚 
ab :wrench: 🔧 
ab :screwdriver: 🪛 
ab :nut_and_bolt: 🔩 
ab :️gear: ⚙ 
ab :️clamp: 🗜 
ab :️balance_scale: ⚖ 
ab :white_cane: 🦯 
ab :link: 🔗 
ab :️chains: ⛓ 
ab :hook: 🪝 
ab :toolbox: 🧰 
ab :magnet: 🧲 
ab :ladder: 🪜 
ab :️alembic: ⚗ 
ab :test_tube: 🧪 
ab :petri_dish: 🧫 
ab :dna: 🧬 
ab :microscope: 🔬 
ab :telescope: 🔭 
ab :satellite_antenna: 📡 
ab :syringe: 💉 
ab :drop_of_blood: 🩸 
ab :pill: 💊 
ab :adhesive_bandage: 🩹 
ab :stethoscope: 🩺 
ab :door: 🚪 
ab :mirror: 🪞 
ab :window: 🪟 
ab :️bed: 🛏 
ab :️couch_and_lamp: 🛋 
ab :chair: 🪑 
ab :toilet: 🚽 
ab :plunger: 🪠 
ab :shower: 🚿 
ab :bathtub: 🛁 
ab :mouse_trap: 🪤 
ab :razor: 🪒 
ab :lotion_bottle: 🧴 
ab :safety_pin: 🧷 
ab :broom: 🧹 
ab :basket: 🧺 
ab :roll_of_paper: 🧻 
ab :bucket: 🪣 
ab :soap: 🧼 
ab :toothbrush: 🪥 
ab :sponge: 🧽 
ab :fire_extinguisher: 🧯 
ab :shopping_cart: 🛒 
ab :cigarette: 🚬 
ab :️coffin: ⚰ 
ab :headstone: 🪦 
ab :️funeral_urn: ⚱ 
ab :moai: 🗿 
ab :placard: 🪧 
ab :potable_water: 🚰 
