" Flags

ab :chequered_flag: 🏁 
ab :red_flag: 🚩 
ab :crossed_flags: 🎌 
ab :black_flag: 🏴 
ab :️white_flag: 🏳 
ab :️transgender_flag: 🏳 ‍⚧️
ab :️rainbow_flag: 🏳    ‍ 
ab :pirate_flag: 🏴      ‍☠️
ab :flag_south_georgia_&_south_sandwich_islands: 🇬 🇸
ab :flag_ascension_island: 🇦                       🇨
ab :flag_andorra: 🇦                                🇩
ab :flag_afghanistan: 🇦                            🇫
ab :flag_antigua_&_barbuda: 🇦                      🇬
ab :flag_anguilla: 🇦                               🇮
ab :flag_albania: 🇦                                🇱
ab :flag_armenia: 🇦                                🇲
ab :flag_angola: 🇦                                 🇴
ab :flag_antarctica: 🇦                             🇶
ab :flag_argentina: 🇦                              🇷
ab :flag_american_samoa: 🇦                         🇸
ab :flag_austria: 🇦                                🇹
ab :flag_australia: 🇦                              🇺
ab :flag_aruba: 🇦                                  🇼
ab :flag_åland_islands: 🇦                          🇽
ab :flag_azerbaijan: 🇦                             🇿
ab :flag_bosnia_&_herzegovina: 🇧                   🇦
ab :flag_barbados: 🇧                               🇧
ab :flag_bangladesh: 🇧                             🇩
ab :flag_belgium: 🇧                                🇪
ab :flag_burkina_faso: 🇧                           🇫
ab :flag_bulgaria: 🇧                               🇬
ab :flag_bahrain: 🇧                                🇭
ab :flag_burundi: 🇧                                🇮
ab :flag_benin: 🇧                                  🇯
ab :flag_st._barthélemy: 🇧                         🇱
ab :flag_bermuda: 🇧                                🇲
ab :flag_brunei: 🇧                                 🇳
ab :flag_bolivia: 🇧                                🇴
ab :flag_united_arab_emirates: 🇦                   🇪
ab :flag_brazil: 🇧                                 🇷
ab :flag_bahamas: 🇧                                🇸
ab :flag_bhutan: 🇧                                 🇹
ab :flag_bouvet_island: 🇧                          🇻
ab :flag_botswana: 🇧                               🇼
ab :flag_belarus: 🇧                                🇾
ab :flag_belize: 🇧                                 🇿
ab :flag_canada: 🇨                                 🇦
ab :flag_cocos_(keeling)_islands: 🇨                🇨
ab :flag_caribbean_netherlands: 🇧                  🇶
ab :flag_congo___kinshasa: 🇨                       🇩
ab :flag_congo___brazzaville: 🇨                    🇬
ab :flag_switzerland: 🇨                            🇭
ab :flag_côte_d’ivoire: 🇨                          🇮
ab :flag_cook_islands: 🇨                           🇰
ab :flag_chile: 🇨                                  🇱
ab :flag_cameroon: 🇨                               🇲
ab :flag_china: 🇨                                  🇳
ab :flag_colombia: 🇨                               🇴
ab :flag_clipperton_island: 🇨                      🇵
ab :flag_costa_rica: 🇨                             🇷
ab :flag_cuba: 🇨                                   🇺
ab :flag_cape_verde: 🇨                             🇻
ab :flag_curaçao: 🇨                                🇼
ab :flag_christmas_island: 🇨                       🇽
ab :flag_cyprus: 🇨                                 🇾
ab :flag_czechia: 🇨                                🇿
ab :flag_germany: 🇩                                🇪
ab :flag_diego_garcia: 🇩                           🇬
ab :flag_djibouti: 🇩                               🇯
ab :flag_denmark: 🇩                                🇰
ab :flag_dominica: 🇩                               🇲
ab :flag_dominican_republic: 🇩                     🇴
ab :flag_algeria: 🇩                                🇿
ab :flag_ceuta_&_melilla: 🇪                        🇦
ab :flag_ecuador: 🇪                                🇨
ab :flag_estonia: 🇪                                🇪
ab :flag_egypt: 🇪                                  🇬
ab :flag_western_sahara: 🇪                         🇭
ab :flag_eritrea: 🇪                                🇷
ab :flag_spain: 🇪                                  🇸
ab :flag_ethiopia: 🇪                               🇹
ab :flag_european_union: 🇪                         🇺
ab :flag_finland: 🇫                                🇮
ab :flag_fiji: 🇫                                   🇯
ab :flag_falkland_islands: 🇫                       🇰
ab :flag_micronesia: 🇫                             🇲
ab :flag_faroe_islands: 🇫                          🇴
ab :flag_france: 🇫                                 🇷
ab :flag_gabon: 🇬                                  🇦
ab :flag_united_kingdom: 🇬                         🇧
ab :flag_grenada: 🇬                                🇩
ab :flag_georgia: 🇬                                🇪
ab :flag_french_guiana: 🇬                          🇫
ab :flag_guernsey: 🇬                               🇬
ab :flag_ghana: 🇬                                  🇭
ab :flag_gibraltar: 🇬                              🇮
ab :flag_greenland: 🇬                              🇱
ab :flag_gambia: 🇬                                 🇲
ab :flag_guinea: 🇬                                 🇳
ab :flag_guadeloupe: 🇬                             🇵
ab :flag_equatorial_guinea: 🇬                      🇶
ab :flag_greece: 🇬                                 🇷
ab :flag_guatemala: 🇬                              🇹
ab :flag_central_african_republic: 🇨               🇫
ab :flag_guam: 🇬                                   🇺
ab :flag_guinea_bissau: 🇬                          🇼
ab :flag_guyana: 🇬                                 🇾
ab :flag_hong_kong_sar_china: 🇭                    🇰
ab :flag_heard_&_mcdonald_islands: 🇭               🇲
ab :flag_honduras: 🇭                               🇳
ab :flag_croatia: 🇭                                🇷
ab :flag_haiti: 🇭                                  🇹
ab :flag_hungary: 🇭                                🇺
ab :flag_canary_islands: 🇮                         🇨
ab :flag_indonesia: 🇮                              🇩
ab :flag_ireland: 🇮                                🇪
ab :flag_israel: 🇮                                 🇱
ab :flag_isle_of_man: 🇮                            🇲
ab :flag_india: 🇮                                  🇳
ab :flag_british_indian_ocean_territory: 🇮         🇴
ab :flag_iraq: 🇮                                   🇶
ab :flag_iran: 🇮                                   🇷
ab :flag_iceland: 🇮                                🇸
ab :flag_italy: 🇮                                  🇹
ab :flag_jersey: 🇯                                 🇪
ab :flag_jamaica: 🇯                                🇲
ab :flag_jordan: 🇯                                 🇴
ab :flag_japan: 🇯                                  🇵
ab :flag_kenya: 🇰                                  🇪
ab :flag_kyrgyzstan: 🇰                             🇬
ab :flag_cambodia: 🇰                               🇭
ab :flag_kiribati: 🇰                               🇮
ab :flag_comoros: 🇰                                🇲
ab :flag_st._kitts_&_nevis: 🇰                      🇳
ab :flag_north_korea: 🇰                            🇵
ab :flag_south_korea: 🇰                            🇷
ab :flag_kuwait: 🇰                                 🇼
ab :flag_cayman_islands: 🇰                         🇾
ab :flag_kazakhstan: 🇰                             🇿
ab :flag_laos: 🇱                                   🇦
ab :flag_lebanon: 🇱                                🇧
ab :flag_st._lucia: 🇱                              🇨
ab :flag_liechtenstein: 🇱                          🇮
ab :flag_sri_lanka: 🇱                              🇰
ab :flag_liberia: 🇱                                🇷
ab :flag_lesotho: 🇱                                🇸
ab :flag_lithuania: 🇱                              🇹
ab :flag_luxembourg: 🇱                             🇺
ab :flag_latvia: 🇱                                 🇻
ab :flag_libya: 🇱                                  🇾
ab :flag_morocco: 🇲                                🇦
ab :flag_monaco: 🇲                                 🇨
ab :flag_moldova: 🇲                                🇩
ab :flag_montenegro: 🇲                             🇪
ab :flag_st._martin: 🇲                             🇫
ab :flag_madagascar: 🇲                             🇬
ab :flag_marshall_islands: 🇲                       🇭
ab :flag_north_macedonia: 🇲                        🇰
ab :flag_mali: 🇲                                   🇱
ab :flag_myanmar_(burma): 🇲                        🇲
ab :flag_mongolia: 🇲                               🇳
ab :flag_macao_sar_china: 🇲                        🇴
ab :flag_northern_mariana_islands: 🇲               🇵
ab :flag_martinique: 🇲                             🇶
ab :flag_mauritania: 🇲                             🇷
ab :flag_montserrat: 🇲                             🇸
ab :flag_malta: 🇲                                  🇹
ab :flag_mauritius: 🇲                              🇺
ab :flag_maldives: 🇲                               🇻
ab :flag_malawi: 🇲                                 🇼
ab :flag_mexico: 🇲                                 🇽
ab :flag_malaysia: 🇲                               🇾
ab :flag_mozambique: 🇲                             🇿
ab :flag_namibia: 🇳                                🇦
ab :flag_new_caledonia: 🇳                          🇨
ab :flag_niger: 🇳                                  🇪
ab :flag_norfolk_island: 🇳                         🇫
ab :flag_nigeria: 🇳                                🇬
ab :flag_nicaragua: 🇳                              🇮
ab :flag_netherlands: 🇳                            🇱
ab :flag_norway: 🇳                                 🇴
ab :flag_nepal: 🇳                                  🇵
ab :flag_nauru: 🇳                                  🇷
ab :flag_niue: 🇳                                   🇺
ab :flag_new_zealand: 🇳                            🇿
ab :flag_oman: 🇴                                   🇲
ab :flag_panama: 🇵                                 🇦
ab :flag_peru: 🇵                                   🇪
ab :flag_french_polynesia: 🇵                       🇫
ab :flag_papua_new_guinea: 🇵                       🇬
ab :flag_philippines: 🇵                            🇭
ab :flag_pakistan: 🇵                               🇰
ab :flag_poland: 🇵                                 🇱
ab :flag_st._pierre_&_miquelon: 🇵                  🇲
ab :flag_pitcairn_islands: 🇵                       🇳
ab :flag_puerto_rico: 🇵                            🇷
ab :flag_palestinian_territories: 🇵                🇸
ab :flag_portugal: 🇵                               🇹
ab :flag_palau: 🇵                                  🇼
ab :flag_paraguay: 🇵                               🇾
ab :flag_qatar: 🇶                                  🇦
ab :flag_réunion: 🇷                                🇪
ab :flag_romania: 🇷                                🇴
ab :flag_serbia: 🇷                                 🇸
ab :flag_russia: 🇷                                 🇺
ab :flag_rwanda: 🇷                                 🇼
ab :flag_saudi_arabia: 🇸                           🇦
ab :flag_solomon_islands: 🇸                        🇧
ab :flag_seychelles: 🇸                             🇨
ab :flag_sudan: 🇸                                  🇩
ab :flag_sweden: 🇸                                 🇪
ab :flag_singapore: 🇸                              🇬
ab :flag_st._helena: 🇸                             🇭
ab :flag_slovenia: 🇸                               🇮
ab :flag_svalbard_&_jan_mayen: 🇸                   🇯
ab :flag_slovakia: 🇸                               🇰
ab :flag_sierra_leone: 🇸                           🇱
ab :flag_san_marino: 🇸                             🇲
ab :flag_senegal: 🇸                                🇳
ab :flag_somalia: 🇸                                🇴
ab :flag_suriname: 🇸                               🇷
ab :flag_south_sudan: 🇸                            🇸
ab :flag_são_tomé_&_príncipe: 🇸                    🇹
ab :flag_el_salvador: 🇸                            🇻
ab :flag_sint_maarten: 🇸                           🇽
ab :flag_syria: 🇸                                  🇾
ab :flag_eswatini: 🇸                               🇿
ab :flag_tristan_da_cunha: 🇹                       🇦
ab :flag_turks_&_caicos_islands: 🇹                 🇨
ab :flag_chad: 🇹                                   🇩
ab :flag_french_southern_territories: 🇹            🇫
ab :flag_togo: 🇹                                   🇬
ab :flag_thailand: 🇹                               🇭
ab :flag_tajikistan: 🇹                             🇯
ab :flag_tokelau: 🇹                                🇰
ab :flag_timor_leste: 🇹                            🇱
ab :flag_turkmenistan: 🇹                           🇲
ab :flag_tunisia: 🇹                                🇳
ab :flag_tonga: 🇹                                  🇴
ab :flag_turkey: 🇹                                 🇷
ab :flag_trinidad_&_tobago: 🇹                      🇹
ab :flag_tuvalu: 🇹                                 🇻
ab :flag_taiwan: 🇹                                 🇼
ab :flag_tanzania: 🇹                               🇿
ab :flag_ukraine: 🇺                                🇦
ab :flag_uganda: 🇺                                 🇬
ab :flag_u.s._outlying_islands: 🇺                  🇲
ab :flag_united_nations: 🇺                         🇳
ab :flag_united_states: 🇺                          🇸
ab :flag_uruguay: 🇺                                🇾
ab :flag_uzbekistan: 🇺                             🇿
ab :flag_vatican_city: 🇻                           🇦
ab :flag_st_vincent_&_grenadines: 🇻               🇨
ab :flag_venezuela: 🇻                              🇪
ab :flag_british_virgin_islands: 🇻                 🇬
ab :flag_us_virgin_islands: 🇻                    🇮
ab :flag_vietnam: 🇻                                🇳
ab :flag_vanuatu: 🇻                                🇺
ab :flag_wallis_&_futuna: 🇼                        🇫
ab :flag_samoa: 🇼                                  🇸
ab :flag_kosovo: 🇽                                 🇰
ab :flag_yemen: 🇾                                  🇪
ab :flag_mayotte: 🇾                                🇹
ab :flag_south_africa: 🇿                           🇦
ab :flag_zambia: 🇿                                 🇲
ab :flag_zimbabwe: 🇿                               🇼
ab :󠁧󠁢󠁥󠁮󠁧󠁿flag_england: 🏴 
ab :󠁧󠁢󠁳󠁣󠁴󠁿flag_scotland: 🏴 
ab :󠁧󠁢󠁷󠁬󠁳󠁿flag_wales: 🏴 
ab :refugee_nation_flag: 🏳 ‍🟧‍⬛‍🟧
ab :󠁵󠁳󠁴󠁸󠁿flag_for_texas_(us_tx): 🏴 
