" Travel & places
ab :person_rowing_boat: 🚣 
ab :map_of_japan: 🗾 
ab :️snow_capped_mountain: 🏔 
ab :️mountain: ⛰ 
ab :volcano: 🌋 
ab :mount_fuji: 🗻 
ab :️camping: 🏕 
ab :️beach_with_umbrella: 🏖 
ab :️desert: 🏜 
ab :️desert_island: 🏝 
ab :️national_park: 🏞 
ab :️stadium: 🏟 
ab :️classical_building: 🏛 
ab :️building_construction: 🏗 
ab :hut: 🛖 
ab :️houses: 🏘 
ab :️derelict_house: 🏚 
ab :house: 🏠 
ab :house_with_garden: 🏡 
ab :office_building: 🏢 
ab :japanese_post_office: 🏣 
ab :post_office: 🏤 
ab :hospital: 🏥 
ab :bank: 🏦 
ab :hotel: 🏨 
ab :love_hotel: 🏩 
ab :convenience_store: 🏪 
ab :school: 🏫 
ab :department_store: 🏬 
ab :factory: 🏭 
ab :japanese_castle: 🏯 
ab :castle: 🏰 
ab :wedding: 💒 
ab :tokyo_tower: 🗼 
ab :statue_of_liberty: 🗽 
ab :church: ⛪ 
ab :mosque: 🕌 
ab :hindu_temple: 🛕 
ab :synagogue: 🕍 
ab :️shinto_shrine: ⛩ 
ab :kaaba: 🕋 
ab :fountain: ⛲ 
ab :tent: ⛺ 
ab :foggy: 🌁 
ab :night_with_stars: 🌃 
ab :️cityscape: 🏙 
ab :sunrise_over_mountains: 🌄 
ab :sunrise: 🌅 
ab :cityscape_at_dusk: 🌆 
ab :sunset: 🌇 
ab :bridge_at_night: 🌉 
ab :carousel_horse: 🎠 
ab :ferris_wheel: 🎡 
ab :roller_coaster: 🎢 
ab :locomotive: 🚂 
ab :railway_car: 🚃 
ab :high_speed_train: 🚄 
ab :bullet_train: 🚅 
ab :train: 🚆 
ab :metro: 🚇 
ab :light_rail: 🚈 
ab :station: 🚉 
ab :tram: 🚊 
ab :monorail: 🚝 
ab :mountain_railway: 🚞 
ab :tram_car: 🚋 
ab :bus: 🚌 
ab :oncoming_bus: 🚍 
ab :trolleybus: 🚎 
ab :minibus: 🚐 
ab :ambulance: 🚑 
ab :fire_engine: 🚒 
ab :police_car: 🚓 
ab :oncoming_police_car: 🚔 
ab :taxi: 🚕 
ab :oncoming_taxi: 🚖 
ab :automobile: 🚗 
ab :oncoming_automobile: 🚘 
ab :sport_utility_vehicle: 🚙 
ab :pickup_truck: 🛻 
ab :delivery_truck: 🚚 
ab :articulated_lorry: 🚛 
ab :tractor: 🚜 
ab :️racing_car: 🏎 
ab :️motorcycle: 🏍 
ab :motor_scooter: 🛵 
ab :auto_rickshaw: 🛺 
ab :bicycle: 🚲 
ab :kick_scooter: 🛴 
ab :bus_stop: 🚏 
ab :️motorway: 🛣 
ab :️railway_track: 🛤 
ab :fuel_pump: ⛽ 
ab :police_car_light: 🚨 
ab :horizontal_traffic_light: 🚥 
ab :vertical_traffic_light: 🚦 
ab :construction: 🚧 
ab :anchor: ⚓ 
ab :sailboat: ⛵ 
ab :speedboat: 🚤 
ab :️passenger_ship: 🛳 
ab :️ferry: ⛴ 
ab :️motor_boat: 🛥 
ab :ship: 🚢 
ab :️airplane: ✈ 
ab :️small_airplane: 🛩 
ab :airplane_departure: 🛫 
ab :airplane_arrival: 🛬 
ab :parachute: 🪂 
ab :seat: 💺 
ab :helicopter: 🚁 
ab :suspension_railway: 🚟 
ab :mountain_cableway: 🚠 
ab :aerial_tramway: 🚡 
ab :️satellite: 🛰 
ab :rocket: 🚀 
ab :flying_saucer: 🛸 
ab :ringed_planet: 🪐 
ab :shooting_star: 🌠 
ab :milky_way: 🌌 
ab :️umbrella_on_ground: ⛱ 
ab :fireworks: 🎆 
ab :sparkler: 🎇 
ab :moon_viewing_ceremony: 🎑 
ab :yen_banknote: 💴 
ab :dollar_banknote: 💵 
ab :euro_banknote: 💶 
ab :pound_banknote: 💷 
ab :moai: 🗿 
ab :passport_control: 🛂 
ab :customs: 🛃 
ab :baggage_claim: 🛄 
ab :left_luggage: 🛅 
